version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: proy3
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tienda
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/sql/procedures.sql:/docker-entrypoint-initdb.d/procedures.sql

  backend:
    build: ./backend
    container_name: node_backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data: