export const styles = {
  app: {
    maxWidth: '960px',
    margin: '0 auto',
    padding: '2rem 1.5rem',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    backgroundColor: '#f5f5f3',
    minHeight: '100vh',
  },
  shell: {
    maxWidth: '960px',
    margin: '0 auto',
  },
  pageTitle: {
    fontSize: '22px',
    fontWeight: '500',
    color: '#1a1a1a',
    marginBottom: '4px',
  },
  pageSub: {
    fontSize: '14px',
    color: '#888780',
    marginBottom: '2rem',
  },
  headerBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '12px',
    marginBottom: '1.5rem',
  },
  headerMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    paddingTop: '8px',
    flexWrap: 'wrap',
  },
  rolBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '6px 12px',
    borderRadius: '20px',
    fontSize: '13px',
    background: '#E6F1FB',
    color: '#185FA5',
    border: '0.5px solid rgba(24,95,165,0.18)',
    fontWeight: '500',
  },
  btnLogout: {
    padding: '6px 14px',
    borderRadius: '8px',
    border: '0.5px solid rgba(0,0,0,0.2)',
    fontSize: '13px',
    cursor: 'pointer',
    background: '#ffffff',
    color: '#888780',
    fontFamily: 'inherit',
  },
  navbar: {
    display: 'flex',
    gap: '8px',
    marginBottom: '1.5rem',
    flexWrap: 'wrap',
  },
  navBtn: {
    padding: '6px 16px',
    borderRadius: '20px',
    fontSize: '13px',
    cursor: 'pointer',
    border: 'none',
    background: 'transparent',
    color: '#888780',
    fontFamily: 'inherit',
  },
  navBtnActive: {
    padding: '6px 16px',
    borderRadius: '20px',
    fontSize: '13px',
    cursor: 'pointer',
    border: 'none',
    background: '#185FA5',
    color: '#E6F1FB',
    fontWeight: '500',
    fontFamily: 'inherit',
  },
  loginWrapper: {
    minHeight: '100vh',
    display: 'grid',
    placeItems: 'center',
    padding: '24px',
    backgroundColor: '#f5f5f3',
  },
  loginCard: {
    width: '100%',
    maxWidth: '420px',
    padding: '28px',
    borderRadius: '12px',
    border: '0.5px solid rgba(0,0,0,0.12)',
    background: '#ffffff',
    boxShadow: '0 10px 30px rgba(0,0,0,0.06)',
  },
  btnPrimary: {
    width: '100%',
    padding: '10px 18px',
    borderRadius: '8px',
    border: '0.5px solid #185FA5',
    fontSize: '14px',
    cursor: 'pointer',
    background: '#185FA5',
    color: '#E6F1FB',
    fontFamily: 'inherit',
  },
  section: {
    background: '#ffffff',
    border: '0.5px solid rgba(0,0,0,0.12)',
    borderRadius: '12px',
    padding: '1.5rem',
    marginBottom: '1.5rem',
  },
  sectionTitle: {
    fontSize: '16px',
    fontWeight: '500',
    color: '#1a1a1a',
    marginBottom: '1.25rem',
    paddingBottom: '0.75rem',
    borderBottom: '0.5px solid rgba(0,0,0,0.1)',
  },
  reportHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '1rem',
    marginBottom: '1rem',
  },
  reportLead: {
    margin: 0,
    fontSize: '14px',
    color: '#888780',
  },
  reportGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: '12px',
    marginBottom: '1.25rem',
  },
  reportCard: {
    border: '0.5px solid rgba(0,0,0,0.12)',
    borderRadius: '14px',
    padding: '14px',
    background: 'linear-gradient(180deg, #ffffff 0%, #fbfcfe 100%)',
  },
  reportCardLabel: {
    fontSize: '12px',
    color: '#888780',
    marginBottom: '6px',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  reportCardValue: {
    fontSize: '22px',
    fontWeight: '600',
    color: '#185FA5',
  },
  reportTableWrap: {
    overflowX: 'auto',
  },
  reportEmpty: {
    padding: '18px',
    borderRadius: '10px',
    background: '#f5f5f3',
    color: '#888780',
    fontSize: '14px',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '14px',
  },
  th: {
    textAlign: 'left',
    padding: '8px 12px',
    fontSize: '12px',
    fontWeight: '500',
    color: '#888780',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    background: '#f5f5f3',
  },
  thFirst: {
    textAlign: 'left',
    padding: '8px 12px',
    fontSize: '12px',
    fontWeight: '500',
    color: '#888780',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    background: '#f5f5f3',
    borderRadius: '6px 0 0 6px',
  },
  thLast: {
    textAlign: 'left',
    padding: '8px 12px',
    fontSize: '12px',
    fontWeight: '500',
    color: '#888780',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    background: '#f5f5f3',
    borderRadius: '0 6px 6px 0',
  },
  td: {
    padding: '10px 12px',
    color: '#1a1a1a',
    borderBottom: '0.5px solid rgba(0,0,0,0.08)',
  },
  tdMuted: {
    padding: '10px 12px',
    color: '#888780',
    fontSize: '13px',
    borderBottom: '0.5px solid rgba(0,0,0,0.08)',
  },
  badgePrice: {
    display: 'inline-block',
    fontSize: '13px',
    fontWeight: '500',
    color: '#0C447C',
    background: '#E6F1FB',
    padding: '2px 8px',
    borderRadius: '20px',
  },
  badgeStock: {
    display: 'inline-block',
    fontSize: '13px',
    fontWeight: '500',
    color: '#3B6D11',
    background: '#EAF3DE',
    padding: '2px 8px',
    borderRadius: '20px',
  },
  btnEdit: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '5px 12px',
    borderRadius: '8px',
    border: '0.5px solid #185FA5',
    fontSize: '13px',
    cursor: 'pointer',
    background: '#E6F1FB',
    color: '#185FA5',
    fontFamily: 'inherit',
    marginRight: '6px',
  },
  btnDelete: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '5px 12px',
    borderRadius: '8px',
    border: '0.5px solid #A32D2D',
    fontSize: '13px',
    cursor: 'pointer',
    background: '#FCEBEB',
    color: '#A32D2D',
    fontFamily: 'inherit',
  },
  btnSubmit: {
    padding: '8px 20px',
    borderRadius: '8px',
    border: '0.5px solid #185FA5',
    fontSize: '14px',
    cursor: 'pointer',
    background: '#185FA5',
    color: '#E6F1FB',
    fontFamily: 'inherit',
  },
  btnCancel: {
    padding: '8px 20px',
    borderRadius: '8px',
    border: '0.5px solid rgba(0,0,0,0.2)',
    fontSize: '14px',
    cursor: 'pointer',
    background: 'transparent',
    color: '#888780',
    fontFamily: 'inherit',
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  label: {
    fontSize: '12px',
    color: '#888780',
    fontWeight: '500',
  },
  input: {
    padding: '8px 10px',
    border: '0.5px solid rgba(0,0,0,0.2)',
    borderRadius: '8px',
    fontSize: '14px',
    background: '#ffffff',
    color: '#1a1a1a',
    fontFamily: 'inherit',
    outline: 'none',
  },
  formActions: {
    display: 'flex',
    gap: '8px',
    marginTop: '1rem',
  },
  alertError: {
    padding: '10px 14px',
    borderRadius: '8px',
    fontSize: '14px',
    marginBottom: '1rem',
    background: '#FCEBEB',
    color: '#A32D2D',
    border: '0.5px solid #F7C1C1',
  },
  alertSuccess: {
    padding: '10px 14px',
    borderRadius: '8px',
    fontSize: '14px',
    marginBottom: '1rem',
    background: '#EAF3DE',
    color: '#3B6D11',
    border: '0.5px solid #C0DD97',
  },
};
